#include "../stub.h"

DEF(envLibInit,        0xFFB51440)
DEF(envCreateHook,     0xFFB51384)
DEF(envDuplicate,      0xFFB512DC)
DEF(envDestroy,        0xFFB512A4)
DEF(envDeleteHook,     0xFFB51274)
DEF(envPrivateCreate,  0xFFB51168)
DEF(envPrivateDestroy, 0xFFB51124)
DEF(putenv,            0xFFB50FC4)
DEF(getenv,            0xFFB50F5C)
DEF(envFind,           0xFFB50EB0)
DEF(envShow,           0xFFB50E28)
