#include "../stub.h"

DEF(intLevelSet,             0xFFB5E5B0)
DEF(intLock,                 0xFFB33EE4)
DEF(intUnlock,               0xFFB33EF8)
DEF(intEnable,               0xFFB5E598)
DEF(intDisable,              0xFFB5E580)
DEF(intConnect,              0xFFB5E514)
DEF(intLockLevelSet,         0xFFB5E504)
DEF(intLockLevelGet,         0xFFB5E4FC)
DEF(intVecTableWriteProtect, 0xFFB5E45C)
DEF(intUninitVecSet,         0xFFB5E3D8)
DEF(intVecBaseSet,           0xFFB5E3D4)
DEF(intVecBaseGet,           0xFFB5E3CC)
