#include "../stub.h"

DEF(selectInit,           0xFFB4A150)
DEF(select,               0xFFB49D10)
DEF(selWakeup,            0xFFB49C10)
DEF(selWakeupAll,         0xFFB49B60)
DEF(selNodeAdd,           0xFFB49AD0)
DEF(selNodeDelete,        0xFFB49A38)
DEF(selWakeupListInit,    0xFFB49A10)
DEF(selWakeupListTerm,    0xFFB49A04)
DEF(selWakeupListLen,     0xFFB499F4)
DEF(selWakeupType,        0xFFB499EC)
