#ifndef MENU_SCRIPTS_H_
#define MENU_SCRIPTS_H_

#include "menupage.h"

enum {
	MENUPAGE_SCRIPTS_EXTAEB,
	MENUPAGE_SCRIPTS_EFLAEB,
	MENUPAGE_SCRIPTS_APTAEB,
	MENUPAGE_SCRIPTS_ISOAEB,
	MENUPAGE_SCRIPTS_INTERVAl,
	MENUPAGE_SCRIPTS_BRAMP,
	MENUPAGE_SCRIPTS_HANDWAVE,
	MENUPAGE_SCRIPTS_TIMER,
	MENUPAGE_SCRIPTS_LEXP,
	MENUPAGE_SCRIPTS_DOFC,
	MENUPAGE_SCRIPTS_COUNT,
	MENUPAGE_SCRIPTS_FIRST = 0,
	MENUPAGE_SCRIPTS_LAST  = MENUPAGE_SCRIPTS_COUNT - 1
};

extern menupage_t menupage_scripts;

#define MENU_SCRIPTS_FL 50 // DOF calculator: initial focal length (mm)
#define MENU_SCRIPTS_FD 10 // DOF calculator: initial focusing distance (m)

typedef enum {
	VIDEO_FORMAT_25FPS,
	VIDEO_FORMAT_30FPS,
	VIDEO_FORMAT_50FPS,
	VIDEO_FORMAT_60FPS,
	VIDEO_FORMAT_COUNT,
	VIDEO_FORMAT_FIRST = 0,
	VIDEO_FORMAT_LAST  = VIDEO_FORMAT_COUNT - 1
} type_VIDEO_FORMAT;

#endif /* MENU_SCRIPTS_H_ */
