#ifndef MENU_PARAMS_H_
#define MENU_PARAMS_H_

#include "menupage.h"

enum {
	MENUPAGE_PARAMS_AUTOISO,
	MENUPAGE_PARAMS_ISO,
	MENUPAGE_PARAMS_AVCOMP,
	MENUPAGE_PARAMS_AEB,
	MENUPAGE_PARAMS_COLOR_TEMP,
	MENUPAGE_PARAMS_NAMED_TEMPS,
	MENUPAGE_PARAMS_MIRROR_LOCKUP,
	MENUPAGE_PARAMS_SAFETY_SHIFT,
	MENUPAGE_PARAMS_IR_REMOTE,
	MENUPAGE_PARAMS_FLASH,
	MENUPAGE_PARAMS_COUNT,
	MENUPAGE_PARAMS_FIRST = 0,
	MENUPAGE_PARAMS_LAST  = MENUPAGE_PARAMS_COUNT - 1
};

extern menupage_t  menupage_params;

#endif /* MENU_PARAMS_H_ */
