#include "../stub.h"

DEF(0xFFA9EA34,FIO_OpenFile)
DEF(0xFFA9EA44,FIO_CreateFile)
DEF(0xFFA9EA54,FIO_RemoveFile)
DEF(0xFFA9EA6C,FIO_ReadFile)
DEF(0xFFA9EA78,FIO_SeekFile)
DEF(0xFFA9EA84,FIO_WriteFile)
DEF(0xFFA9EA90,FIO_CloseFile)
DEF(0xFFA9EAA8,FIO_GetFileSize)
DEF(0xFFA9EAD8,FIO_GetFileAttributes)
DEF(0xFFA9EB3C,FIO_SetFileAttributes)
DEF(0xFFA9EB98,FIO_GetFileTime)
DEF(0xFFA9EBFC,FIO_SetFileTime)
DEF(0xFFA9EC30,FIO_GetFileInfo)
DEF(0xFFA9ECA8,FIO_CreateDirectory)
//DEF(0xFFA9ECB4,FIO_something1) // good candidate for FindNext
//DEF(0xFFA9ECC0,FIO_something2) // good candidate for FindNext
DEF(0xFFA9EEC4,FIO_FindFirst)
//DEF(0xFFA9EF54,FIO_something3) // good candidate for FindNext
//DEF(0xFFA9EFA8,FIO_something4) // good candidate for FindNext
