#include "../stub.h"

DEF(0xFF838F78,GUI_PaletteChange)
DEF(0xFF838FD0,GUI_PalettePush)
DEF(0xFF839008,GUI_PalettePop)
DEF(0xFF936734,GUI_PaletteInit)
DEF(0xFF936770,GUI_PaletteUnInit)

DEF(0xFF93680C,GUI_UnLock)
DEF(0xFF936820,GUI_Lock)
DEF(0xFF832F94,GUI_ClearImage)
DEF(0xFF83302C,GUI_RefreshImage)
DEF(0xFF82B518,GUI_StartMode)

DEF(0xFF840AC4,dialog_event_handler)

DEF(0xFF91496C,CreateDialogBox)
DEF(0xFF914C54,DeleteDialogBox)

DEF(0xFF9163FC,dialog_redraw)
DEF(0xFF837FA8,dialog_item_set_str)
DEF(0xFF8382DC,dialog_item_set_int)
DEF(0xFF915FFC,dialog_item_set_label)
DEF(0xFF936144,window_instance_redraw)

DEF(0xFF914F94,GUI_Select_Item)
DEF(0xFF838714,GUI_Highlight_Sub)
DEF(0xFF838748,GUI_Disable_Item)

DEF(0xFF84ED98,SetTurnDisplayEvent_1_after_2)
DEF(0xFF84EDC0,SetTurnDisplayEvent_2_after_1)

DEF(0x00001ECC,GUIMode)
DEF(0x00006D58,DisplayOn)
DEF(0x00001ED0,GUIIdleFlag)

DEF(0xFF8290D0,GUI_IDLEHandler)
